In [41]:
from tensorflow.keras.models import load_model
import pandas as pd 
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

In [42]:
loaded_model = load_model('model.h5')

In [43]:
x_train=pd.read_csv('data/data_processed/x_data.csv').drop(['Unnamed: 0'], axis=1)
y_train=pd.read_csv('data/data_processed/y_data.csv').drop(['Unnamed: 0'], axis=1)

In [44]:
y_train

failure
0             0
1             4
2             4
3             4
4             4
...         ...
169033        0
169034        0
169035        0
169036        0
169037        0

[169038 rows x 1 columns]

In [45]:
dict_map = {'none': 0, 
            'comp1': 1, 
            'comp2': 2, 
            'comp3': 3,
            'comp4': 4, 
           }
def get_key(value):
    keys=[key for key,val in dict_map.items() if val==value ]
    return keys[0]


In [46]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
predictions = loaded_model.predict(x_train[[4]])

1/1 [==============================] - 0s 74ms/step


In [47]:
binary_predictions = (predictions > 0.5).astype(int)
print("component expected to fail:",get_key(binary_predictions[0][0]))

component expected to fail: comp1


In [48]:
y_pred=[]

In [49]:
for i in range(0,5001):
    predictions = loaded_model.predict(x_train[[i]])
    y_pred.append((predictions > 0.5).astype(int))

1/1 [==============================] - 0s 23ms/step
0
1/1 [==============================] - 0s 18ms/step
1
1/1 [==============================] - 0s 35ms/step
2
1/1 [==============================] - 0s 43ms/step
3
1/1 [==============================] - 0s 33ms/step
4
1/1 [==============================] - 0s 25ms/step
5
1/1 [==============================] - 0s 27ms/step
6
1/1 [==============================] - 0s 16ms/step
7
1/1 [==============================] - 0s 23ms/step
8
1/1 [==============================] - 0s 17ms/step
9
1/1 [==============================] - 0s 20ms/step
10
1/1 [==============================] - 0s 26ms/step
11
1/1 [==============================] - 0s 23ms/step
12
1/1 [==============================] - 0s 28ms/step
13
1/1 [==============================] - 0s 35ms/step
14
1/1 [==============================] - 0s 30ms/step
15
1/1 [==============================] - 0s 32ms/step
16
1/1 [==============================] - 0s 42ms/step
17
1/1 [===============

In [50]:
y_pred=np.array(y_pred)
y_train2=np.array(y_train)
y_pred=np.reshape(y_pred,(5001,1))

In [51]:
precision = precision_score(y_train2[0:5001], y_pred,average='weighted')
recall = recall_score(y_train2[0:5001], y_pred,average='weighted')
f1 = f1_score(y_train2[0:5001], y_pred,average='weighted')
conf_matrix = confusion_matrix(y_train2[0:5001], y_pred)

C:\Users\acer\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [60]:
print(f'precision : {precision}\nRecall : {recall}\nf1 : {f1}\nconfusion matrix :\n {conf_matrix}')

precision : 0.9842342798352286
Recall : 0.9882023595280944
f1 : 0.9856089227026286
confusion matrix :
 [[4922    2    0    0]
 [   5   20    0    0]
 [   4   30    0    0]
 [   0   18    0    0]]
